[global]
   workgroup = WORKGROUP
   server string = SageDrive SMB Proxy
   security = user
   map to guest = Bad User
   log file = /var/log/samba/%m.log
   max log size = 50
   oplocks = no
   kernel oplocks = no
   strict allocate = yes

[GoogleDrive]
   path = /mnt/gdrive
   public = yes
   writable = yes
   guest ok = yes
   force user = root
